// Every user-facing string lives here so the UI can be translated later.
// Functions build strings that need numbers or names; keep sentence case throughout.

const plural = (n: number, one: string, other: string) => (n === 1 ? one : other);

export const strings = {
  app: {
    name: "Backsight",
    tagline: "A desktop viewer for Tapo cameras",
    skipToContent: "Skip to content",
  },

  nav: {
    label: "Main",
    cameras: "Cameras",
    multiview: "Multi-view",
    downloads: "Downloads",
    settings: "Settings",
    collapse: "Collapse sidebar",
    expand: "Expand sidebar",
    activeJobs: (n: number) => `${n} ${plural(n, "download", "downloads")} in progress`,
    onlineSummary: (online: number, total: number) => `${online} of ${total} online`,
  },

  /** Key caps shown in hints and tooltips. */
  keys: {
    esc: "Esc",
    space: "Space",
    live: "L",
    speed: "[ ]",
  },

  common: {
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    continue: "Continue",
    done: "Done",
    save: "Save",
    saving: "Saving…",
    remove: "Remove",
    rename: "Rename",
    retry: "Try again",
    loading: "Loading…",
    more: "More",
    show: "Show",
    hide: "Hide",
    optional: "Optional",
    new: "New",
    edit: "Edit",
    copy: "Copy",
    copied: "Copied",
    reset: "Reset",
    delete: "Delete",
  },

  status: {
    online: "Online",
    connecting: "Connecting…",
    offline: "Offline",
    offlineSince: (ago: string) => `Offline · seen ${ago}`,
    privacy: "Privacy mode",
    locked: (mins: number) => (mins <= 0 ? "Locked — retry now" : `Locked — retry in ${formatMinutes(mins)}`),
    lockedShort: "Locked",
    authFailed: "Password rejected",
    unsupported: "Not supported",
  },

  statusDetail: {
    offline: "Backsight can't reach this camera. Check that it's powered on and connected to your network.",
    privacy: "The camera won't stream or record while privacy mode is on. Turn it off in the Tapo app.",
    locked: (mins: number) =>
      mins <= 0
        ? "Too many failed sign-ins locked this camera. It should accept a login again now."
        : `Too many failed sign-ins locked this camera. It accepts logins again in ${formatMinutes(mins)}.`,
    authFailed: "The camera rejected the saved password. Update it in Settings.",
    unsupported: "This model or firmware isn't supported yet.",
    connecting: "Connecting to the camera…",
  },

  relative: {
    justNow: "just now",
    minutes: (n: number) => `${n} min ago`,
    hours: (n: number) => `${n} h ago`,
    yesterday: "yesterday",
    days: (n: number) => `${n} days ago`,
  },

  home: {
    title: "Cameras",
    greeting: {
      morning: "Good morning",
      afternoon: "Good afternoon",
      evening: "Good evening",
    },
    subtitle: (online: number, total: number, attention: number) =>
      attention > 0
        ? `${online} of ${total} online · ${attention} ${plural(attention, "needs", "need")} attention`
        : `${online} of ${total} online`,
    addCamera: "Add camera",
    groupsLabel: "Camera groups",
    all: "All",
    favorites: "Favorites",
    live: "Live",
    playback: "Playback",
    favorite: "Add to favorites",
    unfavorite: "Remove from favorites",
    open: (name: string) => `Open ${name}`,
    noPreview: "No preview yet",
    gettingPreview: "Getting a preview…",
    emptyTitle: "No cameras yet",
    emptyBody: "Add a Tapo camera on your network to watch it live and browse its SD card from your desktop.",
    emptyChecklistTitle: "You'll need",
    emptyChecklist: [
      "The camera on the same network as this computer",
      "Third-Party Compatibility turned on in the Tapo app",
      "The password of the TP-Link account that owns the camera",
    ],
    groupEmptyTitle: "Nothing here yet",
    favoritesEmpty: "Star a camera to pin it here.",
    groupEmpty: "Add cameras to this group in Settings.",
    loadError: "Couldn't load your cameras.",
  },

  storage: {
    label: "SD card",
    usage: (used: string, total: string) => `${used} of ${total}`,
    loop: (total: string) => `${total} · loop recording`,
    none: "No SD card",
    checking: "Checking…",
    unknown: "Unknown",
    unformatted: "Needs formatting",
    full: "Full",
    error: "Card error",
    mode: {
      continuous: "Continuous",
      detection: "Detection only",
      off: "Recording off",
    },
  },

  addCamera: {
    title: "Add a camera",
    findDescription: "Backsight looks for Tapo cameras on your local network.",
    scanning: "Scanning your network…",
    scanningHint: "This takes a few seconds.",
    found: (n: number) => `${n} ${plural(n, "device", "devices")} found`,
    rescan: "Scan again",
    noneFound: "No cameras found",
    noneFoundBody: "Make sure this computer and your cameras are on the same network, or enter an IP address below.",
    alreadyAdded: "Added",
    notSupported: "Not a camera",
    kind: {
      camera: "Camera",
      doorbell: "Doorbell",
      hub: "Hub",
      other: "Device",
    },
    unnamed: "Tapo device",
    manualLabel: "Or enter an IP address",
    manualPlaceholder: "192.168.1.20",
    manualInvalid: "Enter an IP address like 192.168.1.20, or a host name.",
    credentialsTitle: "Sign in to the camera",
    credentialsDescription: "The camera checks these details itself, on your network.",
    change: "Change",
    nameLabel: "Name",
    namePlaceholder: "e.g. Front Door",
    passwordLabel: "TP-Link account password",
    passwordHelp:
      "The password you use to sign in to the Tapo app. The camera checks it locally; Backsight never sends it to TP-Link or anywhere else, and keeps it in your system keychain.",
    passwordRequired: "Enter the TP-Link account password.",
    cameraAccount: "Camera Account (RTSP)",
    cameraAccountHelp:
      "Optional. Enables live view over RTSP. Create it in the Tapo app: camera settings → Advanced Settings → Camera Account.",
    username: "Username",
    password: "Password",
    groupsLabel: "Groups",
    compatTitle: "Turn on Third-Party Compatibility first",
    compatBody: "Backsight talks to your camera the way other local apps do, which the Tapo app has to allow.",
    compatSteps: ["Open the Tapo app", "Go to Me → Third-Party Services", "Turn on Third-Party Compatibility"],
    compatToggle: "How do I turn it on?",
    submit: "Add camera",
    submitting: "Checking…",
    lockedWait: (mins: number) => `Try again in ${formatMinutes(mins)}`,
    successTitle: (name: string) => `${name} is ready`,
    successBody: "The camera is saved. You can watch it live or browse its recordings.",
    openLive: "Open live view",
    toast: (name: string) => `${name} added`,
  },

  errors: {
    camera_locked: {
      title: "Camera is locked",
      body: (mins: number, at: string) =>
        mins <= 0
          ? "Too many failed sign-ins locked this camera. It should accept a login again now."
          : `Too many failed sign-ins locked this camera. It accepts logins again in ${formatMinutes(mins)}, at ${at}.`,
    },
    auth_failed: {
      title: "Password not accepted",
      body: "Use the password of the TP-Link account that owns this camera — the one you sign in to the Tapo app with.",
      hint: "After 10 failed attempts the camera locks logins for about 30 minutes.",
    },
    third_party_compat_off: {
      title: "Third-Party Compatibility is off",
      body: "Turn it on in the Tapo app: Me → Third-Party Services → Third-Party Compatibility. Then try again.",
    },
    playback_busy: {
      title: "Playback is busy",
      body: "Another app is playing back this camera's SD card. Only one client can do that at a time.",
    },
    stream_limit: {
      title: "Too many viewers",
      body: "This camera allows three live viewers at once, including NVR software. Close one and try again.",
    },
    offline: {
      title: "Camera is offline",
      body: "Backsight can't reach the camera. Check that it's powered on and on the same network.",
    },
    privacy_mode: {
      title: "Privacy mode is on",
      body: "The camera won't stream or record while privacy mode is on. Turn it off in the Tapo app.",
    },
    unsupported: {
      title: "Not supported yet",
      body: "This camera's model or firmware isn't supported yet.",
    },
    not_found: {
      title: "Not found",
      body: "It may have been removed.",
    },
    invalid_input: {
      title: "Check the details",
      body: "Something in the form isn't quite right.",
    },
    internal: {
      title: "Something went wrong",
      body: "An unexpected error occurred.",
    },
  },

  camera: {
    back: "Cameras",
    tabs: { live: "Live", playback: "Playback" },
    tabsLabel: "View",
    notFoundTitle: "Camera not found",
    notFoundBody: "It may have been removed.",
    backHome: "Back to cameras",
    menu: "Camera options",
    settings: "Camera settings",
  },

  live: {
    badge: "Live",
    rec: "REC",
    quality: "Quality",
    hd: "HD",
    sd: "SD",
    mute: "Mute",
    unmute: "Unmute",
    snapshot: "Snapshot",
    record: "Record",
    stopRecording: "Stop",
    sound: "Sound",
    fullscreen: "Fullscreen",
    exitFullscreen: "Exit fullscreen",
    stats: "Stream info",
    statsWaiting: "Waiting for video…",
    statsRows: {
      codec: "Codec",
      resolution: "Resolution",
      fps: "Frame rate",
      bitrate: "Bitrate",
      dropped: "Dropped frames",
      queue: "Decode queue",
      latency: "Latency",
    },
    snapshotSaved: "Snapshot saved",
    snapshotFailed: "Couldn't capture a snapshot",
    recordStarted: "Recording — Backsight will export this stretch from the SD card when you stop.",
    recordSaved: "Recording added to Downloads",
    recordUnavailable: "Recording needs an SD card that's recording.",
    tiles: {
      noVideo: "No video yet",
      used: (pct: string) => `${pct} used`,
      loop: "Loop recording",
      connection: "Connection",
      stream: "Stream",
      storage: "SD card",
      device: "Device",
      localTime: "Camera time",
    },
    todayTitle: "Today",
    todayEmpty: "No events so far today.",
    seeAll: "Open in Playback",
    connecting: "Connecting…",
    buffering: "Buffering…",
    streamError: "The stream stopped",
    codecUnsupported: "This computer can't decode the camera's video format.",
    reconnect: "Reconnect",
  },

  playback: {
    prevDay: "Previous day",
    nextDay: "Next day",
    chooseDate: "Choose a date",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    hasRecordings: "has recordings",
    noRecordingsDay: "No recordings on this day",
    noRecordingsDayBody: "Pick another day — days with footage have a dot in the calendar.",
    play: "Play",
    pause: "Pause",
    mute: "Mute",
    unmute: "Unmute",
    snapshot: "Snapshot",
    clip: "Clip",
    fullscreen: "Fullscreen",
    exitFullscreen: "Exit fullscreen",
    speed: "Speed",
    speedValue: (s: number) => `${s}×`,
    live: "Live",
    goLive: "Back to live",
    shortcuts: "Keyboard shortcuts",
    shortcutList: [
      ["Space", "Play or pause"],
      ["← →", "Back or forward 10 seconds"],
      ["Shift + ← →", "Back or forward 1 minute"],
      ["[ ]", "Slower or faster"],
      ["Home End", "Start or end of the day"],
      ["L", "Back to live"],
      ["Wheel", "Zoom the timeline"],
      ["Drag, Shift + wheel", "Pan the timeline"],
    ] as [string, string][],
    endOfDay: "End of recordings for this day",
    nextDayCta: "Next day",
    offlineTitle: "Playback isn't available",
    events: {
      title: (n: number) => `Detected Events (${n})`,
      filterLabel: "Filter events by type",
      all: "All",
      empty: "No detection events on this day.",
      emptyFiltered: "No events match these filters.",
      clearFilters: "Clear filters",
      menu: "Event options",
      playFrom: "Play from here",
      clipEvent: "Clip this event",
      copyTime: "Copy time",
      timeCopied: "Time copied",
      nowPlaying: "Playing",
      listLabel: "Detection events",
    },
    today: "Today",
    yesterday: "Yesterday",
    recordingsLegend: "Has recordings",
    timeline: {
      footage: "Recorded",
      label: "Playback position",
      backToPlayhead: "Back to playhead",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      now: "Now",
    },
  },

  clip: {
    title: "Clip",
    close: "Close clip editor",
    selectedLength: "Selected length",
    start: "Clip start",
    end: "Clip end",
    longWarning: "Clips over an hour take a while to export and can use several gigabytes.",
    submit: "Clip & Download",
    submitting: "Adding…",
    toastTitle: "Clip added to Downloads",
    toastAction: "View",
    failed: "Couldn't start the export",
    hint: "Drag the brackets to choose the start and end.",
  },

  multiview: {
    title: "Multi-view",
    layout: "Layout",
    layouts: {
      "1": "Single",
      "2": "Two",
      "4": "Four",
      "1+5": "One large, five small",
      "9": "Nine",
      "16": "Sixteen",
    },
    page: (n: number, total: number) => `Page ${n} of ${total}`,
    prevPage: "Previous page",
    nextPage: "Next page",
    live: "Live",
    emptySlot: "No camera",
    addCamera: "Add camera",
    focus: (name: string) => `Focus ${name}`,
    exitFocus: "Back to grid",
    unmute: (name: string) => `Unmute ${name}`,
    mute: (name: string) => `Mute ${name}`,
    openCamera: "Open camera",
    reorderHint: "Drag tiles to reorder. Double-click a tile to focus it.",
    dragHandle: (name: string) => `Reorder ${name}`,
    noCamerasTitle: "No cameras to show",
    noCamerasBody: "Add a camera to build your wall of live views.",
    dnd: {
      pickUp: (name: string) => `Picked up ${name}.`,
      over: (name: string, pos: number) => `${name} is over position ${pos}.`,
      drop: (name: string, pos: number) => `${name} dropped at position ${pos}.`,
      cancel: (name: string) => `Reordering cancelled. ${name} returned to its place.`,
      instructions:
        "To pick up a tile, press space or enter. Use the arrow keys to move it, space or enter to drop it, and escape to cancel.",
    },
  },

  downloads: {
    title: "Downloads",
    savedTo: "Clips are saved to",
    changeFolder: "Change folder",
    inProgress: "In progress",
    finished: "Finished",
    state: {
      queued: "Queued",
      running: "Exporting",
      paused: "Paused",
      done: "Done",
      failed: "Failed",
      cancelled: "Cancelled",
    },
    pausedHint: "Waiting for live view or playback on this camera to finish",
    cancel: "Cancel",
    reveal: "Show in folder",
    retry: "Export again",
    eta: (text: string) => `${text} left`,
    progress: (pct: string, size: string) => `${pct} · ${size}`,
    emptyTitle: "No downloads yet",
    emptyBody: "Use the scissors in Playback to clip a moment and save it as an MP4.",
    goToCameras: "Go to cameras",
    completedToast: "Clip ready",
    failedToast: "Export failed",
    cancelledToast: "Export cancelled",
    revealFailed: "Couldn't open the folder",
  },

  settings: {
    title: "Settings",
    subtitle: "Appearance, exports and your cameras",
    sections: {
      appearance: "Appearance",
      recordings: "Recordings & export",
      cameras: "Cameras",
      groups: "Groups",
      about: "About",
    },
    theme: "Theme",
    themeHelp: "Backsight follows your system's reduced-motion setting.",
    themes: { system: "System", light: "Light", dark: "Dark" },
    exportDir: "Export folder",
    exportDirHelp: "Where clips and snapshots are saved.",
    choose: "Choose…",
    chooseUnavailable: "The folder picker is available in the desktop app.",
    nameTemplate: "File name",
    nameTemplateHelp: "Insert a token to build the name. The .mp4 extension is added for you.",
    nameTemplateEmpty: "The file name can't be empty.",
    preview: "Preview",
    sampleCamera: "Front Door",
    tokens: { camera: "Camera", date: "Date", start: "Start", end: "End" },
    cacheLimit: "Thumbnail and index cache",
    cacheLimitHelp: "Older cached thumbnails are removed when the cache grows past this size.",
    defaultQuality: "Default live quality",
    defaultQualityHelp: "SD uses less bandwidth; multi-view always uses SD for small tiles.",
    saved: "Settings saved",
    saveFailed: "Couldn't save settings",
    camerasEmpty: "No cameras yet.",
    renameLabel: (name: string) => `Rename ${name}`,
    updatePassword: "Update password",
    updatePasswordTitle: (name: string) => `Update password for ${name}`,
    updatePasswordBody: "Enter the current password of the TP-Link account that owns this camera.",
    passwordUpdated: "Password updated",
    removeCamera: "Remove camera",
    removeTitle: (name: string) => `Remove ${name}?`,
    removeBody:
      "Backsight forgets this camera and its saved password. Recordings on the camera's SD card aren't affected.",
    removed: (name: string) => `${name} removed`,
    groupsHelp: "Groups appear as tabs on the Cameras page.",
    newGroup: "New group",
    groupName: "Group name",
    deleteGroup: (name: string) => `Delete ${name}`,
    renameGroup: (name: string) => `Rename ${name}`,
    groupsEmpty: "No groups yet.",
    favorite: "Favorite",
    cameraGroups: "Groups",
    version: (v: string) => `Version ${v}`,
    aboutBody:
      "An open-source desktop viewer for Tapo cameras. It talks to your cameras directly on your local network — nothing goes through a cloud service.",
    license: "Released under the MIT License.",
    credits: "Credits",
    creditsBody: "Backsight builds on community reverse-engineering work:",
    disclaimerTitle: "Disclaimer",
    disclaimer:
      "Backsight is an independent, unofficial project. It is not affiliated with, endorsed by, or supported by TP-Link. 'Tapo' and 'TP-Link' are trademarks of their respective owners and are used only to describe compatibility. Provided as is, without warranty.",
  },

  notFound: {
    title: "Page not found",
    body: "That page doesn't exist.",
    home: "Go to cameras",
  },

  events: {
    motion: "Motion",
    person: "Person",
    vehicle: "Vehicle",
    pet: "Pet",
    baby_cry: "Baby crying",
    line_crossing: "Line crossing",
    area_intrusion: "Area intrusion",
    tamper: "Camera tampering",
    sound: "Sound",
    doorbell: "Doorbell",
    other: "Other",
  },
} as const;

/** "23 min", "1 h 5 min" */
export function formatMinutes(mins: number): string {
  if (mins < 60) return `${mins} min`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m === 0 ? `${h} h` : `${h} h ${m} min`;
}

export type Strings = typeof strings;
